canPlaceSnowOn:
  - snow_block
  - quartz_block

itemsAbleToBreakSnow:
  - wooden_shovel
  - stone_shovel
  - iron_shovel
  - golden_shovel
  - diamond_shovel
  - netherite_shovel

lives: 5
world: world
location: 0 64 0
respawn-delay: 6
crafted-snow-amount: 2
spawn-locations: []

messages:
  playerDiedBroadcast: '§c§l{player}§c est mort !§e Il lui reste §l{lives}§e vies. §6§l{remaining}§6 joueurs restant !'
  playerDiedTitle: '§4Tu es mort !'
  playerDiedSubtitle: '§6 Il te reste §l{lives}§6 vies.§3 Tu pourras Réapparaître dans §l{time}s§3.'
  playerDiedForeverSubtitle: '§cTu ne pourras plus réapparaître, tu n''as plus de vies.'
  noPerm: '§cVous n''avez pas la permssion {perm}'
  join: '§aTu as rejoint le jeu de §lSnow Wars§a !'
  alreadyJoined: '§eTu avais déjà rejoint, mais je te retéléporte ici si tu veux.'
  youResuscitated: '§2Tu a été ressuscité !'

