# GitHub: https://github.com/bananasmoothii/SnowWars
# Discord: https://discord.gg/HNHfEJXwbs
# WARNING: All comments below will be gone after the first command that refreshes the config, if you want to find
# a new config you can delete this one or go in https://github.com/bananasmoothii/SnowWars/blob/master/src/main/resources/config.yml
# WARNING 2: Make a backup of your world because the plugin will mess with player inventories, locations, gamemodes...

# blocks on which you can place snow in gamemode adventure
can-place-snow-on:
  - snow_block
  - snow
  - chiseled_quartz_block

items-able-to-break-snow:
  - wooden_shovel
  - stone_shovel
  - iron_shovel
  - golden_shovel
  - diamond_shovel
  - netherite_shovel

# lives at new game for each player
lives: 5
# world for the main spawn location, set via /snowwars setmainspawn
world: world
# main spawn location, set via /snowwars setmainspawn, can be X Y Z or X Y Z Yaw Pitch
location: 0 64 0
# delay in seconds before I dead player respawns
respawn-delay: 20
# modifies the craft of snow to make 2 of them each time
crafted-snow-amount: 2
# if the players falls more than X blocks down, he instantly gets killed. Set to 0 to disable.
max-fall-height: 20.0
# interval in ticks. When someone breaks a snow block, if snow blocks aren't bind to a block from the "canPlaceOn" list (appart from snow blocks and snow),
# they recursively get break.
snow-block-break-interval: 3
# set given at each players. This uses commands, so for example "sand" will become "/minecraft:give <player> sand".
# This allows to put nbt tags and amounts to each item.
start-set:
  - stone_shovel{ench:{id:34,lvl:2}}
  - snow_ball 16
# whether to give these items only at the beginning or at each respawn
give-set-at-respawn: true
# set via /snowwars addspawn
spawn-locations: []

messages:
  playerDiedBroadcast: '§c§l{player}§c died!§e He has §l{lives}§e lives left. §6§l{remaining}§6 players remaining!'
  playerKilledBroadcast: '§c§l{killer}§c killed §l{victim}§e!§e He has §l{lives}§e lives left. §6§l{remaining}§6 players remaining!'
  playerDiedTitle: '§4You died !'
  playerDiedSubtitle: '§6You have §l{lives}§6 lives left.§3 You will respawn in §l{time}§3.'
  playerDiedForeverSubtitle: '§cYou won''t respawn as you have no more lives.'
  noPerm: '§cYou don''t have the permission {perm}'
  join: '§aYou joined the §lSnow Wars§a game!'
  alreadyJoined: '§eYou already joined, but I can teleport you here if you want.'
  youResuscitated: '§2You got respawned!'
  playerWon: '§b§l§n{player}§b won!'
  alreadyStarted: '§eYou can''t do that as the game already started!'

