# GitHub: https://github.com/bananasmoothii/SnowWars
# Discord: https://discord.gg/HNHfEJXwbs
# WARNING: All comments below will be gone after the first command that refreshes the config, if you want to find
# a new config you can delete this one or go in https://github.com/bananasmoothii/SnowWars/blob/master/src/main/resources/config.yml

# blocks on which you can place snow in gamemode adventure
canPlaceSnowOn:
  - snow_block
  - snow
  - quartz_block

itemsAbleToBreakSnow:
  - wooden_shovel
  - stone_shovel
  - iron_shovel
  - golden_shovel
  - diamond_shovel
  - netherite_shovel

# lives at new game for each player
lives: 5
# world for the main spawn location, set via /snowwars setmainspawn
world: world
# main spawn location, set via /snowwars setmainspawn, can be X Y Z or X Y Z Yaw Pitch
location: 0 64 0
# delay in seconds before I dead player respawns
respawn-delay: 6
# modifies the craft of snow to make 2 of them each time
crafted-snow-amount: 2
# set via /snowwars addspawn
spawn-locations: []

messages:
  playerDiedBroadcast: '§c§l{player}§c died!§e He has §l{lives}§e lives left. §6§l{remaining}§6 players remaining!'
  playerDiedTitle: '§4You died !'
  playerDiedSubtitle: '§6You have §l{lives}§6 lives left.§3 You will respawn in §l{time}s§3.'
  playerDiedForeverSubtitle: '§cYou won''t respawn as you have no more lives.'
  noPerm: '§cYou don''t have the permission {perm}'
  join: '§aYou joined the §lSnow Wars§a game!'
  alreadyJoined: '§eYou already joined, but I can teleport you here if you want.'
  youResuscitated: '§2You got respawned!'
  playerWon: '§b§l§n{player}§b won!'

