name: SnowWars
version: ${project.version}
main: fr.bananasmoothii.snowwars.SnowWarsPlugin
api-version: 1.16
authors: [ Bananasmoothii ]
description: This plugin is a minigame plugin for running a snow wars
