name: SnowWars
version: ${project.version}
main: fr.bananasmoothii.snowwars.SnowWarsPlugin
api-version: 1.16
authors: [ Bananasmoothii ]
description: This plugin is a minigame plugin for running a snow wars
depend:
  - FastAsyncWorldEdit

commands:
  snowwars:
    description: Main SnowWars command
    usage: /snowwars join|quit|start|forcestart|stop|addspawn|setmainspawn|reload|setsource|iceevent|refreshmap|addlive
